'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.ComponentModel.DataAnnotations

Partial Public Class category
    <Key>
    Public Property category_id As Integer

    <DisplayName("Category Name")>
    <Required>
    Public Property name As String

    Public Overridable Property products As ICollection(Of product) = New HashSet(Of product)

End Class
