'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.ComponentModel.DataAnnotations

Partial Public Class product
    <Key>
    <Required>
    <Range(0, 10000, ErrorMessage:="Id must be larger than 0")>
    <DisplayName("Product Id")>
    Public Property product_id As Integer

    <Required>
    <DisplayName("Product Name")>
    Public Property name As String

    <Required>
    <Range(1, 10000, ErrorMessage:="Quantity must be larger than 0 and Smaller than 10000")>
    <DisplayName("Product Quantity")>
    Public Property quantity As Integer

    <DisplayName("Category Name")>
    Public Property category_id As Integer

    <DisplayName("Product Image")>
    Public Property image As String

    Public Overridable Property category As category

End Class
